config/routes.rb
Rails.application.routes.draw do
    
  namespace :admin do
    resources :order_details, only: [:update]
  end
  
  namespace :admin do
    resources :orders, only: [:show, :update]
  end
  
  namespace :admin do
    resources :customers
  end
  
  namespace :admin do
    resources :genres
  end
  
  namespace :admin do
    resources :items
  end
  
  namespace :admin do
  root  "homes#top"
  end

  scope module: 'public' do
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  
  scope module: 'public' do
      post "orders/confirm", to: "orders#confirm"
      get "orders/complete", to: "orders#complete"
      resources :orders
  end
  
  scope module: 'public' do
    delete '/cart_items/destroy_all', to: "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  
  scope module: 'public' do
      get '/customers/mypage', to: "customers#show"
      get '/customers/information/edit', to: "customers#edit"
      patch '/customers/information', to: "customers#update"
      get '/customers/unsubscribe', to: "customers#unsubscribe"
      patch '/customers/withdraw', to: "customers#withdraw"
  end
  
  scope module: 'public' do
      resources :items, only: [:index, :show]
  end
  

  scope module: 'public' do
  root to: "homes#top"
  get '/about', to: "homes#about"
  end

  devise_for :customers, path: 'customers', controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  
  devise_for :admin, skip: [:registrations, :passwords], path: 'admin', controllers: {
  sessions: "admin/sessions"
 }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items
  has_many :orders
  has_many :addresses
  
   def full_name
         self.last_name + " " + self.first_name
   end
   
   def full_name_kana
       self.last_name_kana + " " + self.first_name_kana
   end
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
        @customer = Customer.find(params[:id])
    
    if  @customer.update(customer_params)
        redirect_to admin_customer_path(@customer.id)
        flash[:notice] = "会員情報が更新されました。"
    else
        render :edit
    end
  end
  
  private
  
   def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, 
                               :postal_code, :address, :telephone_number, :is_deleted)
   end
   
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  protected
  # strong parameterで姓と名の属性(firstNameとlastName)をpermitする
    def configure_permitted_parameters
       devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name,:last_name_kana, :first_name_kana, 
                                       :postal_code, :address, :telephone_number])
    end
  
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    public_homes_top_path
  end

  def after_sign_out_path_for(resource)
    new_customer_session_path
  end
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
 def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
 end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
<div class="col-5 mt-5 mb-5 secondary text-center">
<h2><%= @customer.full_name %>さんの会員詳細</h2>
</div>
</div>

<div class="container">
<div class="col-7 mx-auto">
    
<%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>

<div class="field row pb-2">
<label for ="customer_id" class="col-3">会員ID</label>
<div class="col-9">
<%= @customer.id %>
</div>
</div>

<div class="form-group row pb-2">
<label for ="customer_name"  class="col-3 col-form-label">氏名</label>
<div class="col-9 row ml-0">
<%= f.text_field :last_name, class:"form-control col-6" %><%= f.text_field :first_name, class:"form-control col-6" %>
</div>
</div>

<div class="form-group row pb-2">
<label for ="customer_name_kana" class="col-3 col-form-label">フリガナ</label>
<div class="col-9 row ml-0">
<%= f.text_field :last_name_kana, class:"form-control col-6" %><%= f.text_field :first_name_kana, class:"form-control col-6" %>
</div>
</div>

<div class="form-group row pb-2">
<label for ="customer_postal_code" class="col-3 col-form-label">郵便番号</label>
<div class="col-sm-auto">
<%= f.text_field :postal_code, class:"form-control" %>
</div>
</div>

<div class="form-group row pb-2">
<label for ="customer_name_kana" class="col-3 col-form-label">住所</label>
<div class="col-9">
<%= f.text_area :address, class:"form-control" %>
</div>
</div>

<div class="form-group row pb-2">
<label for ="customer_name_kana" class="col-3 col-form-label">電話番号</label>
<div class="col-sm-auto">
<%= f.text_field :telephone_number, class:"form-control" %>
</div>
</div>

<div class="form-group row pb-2">
<label for ="is_active" class="col-3 col-form-label">会員ステータス</label>
<div class="col-9">
<%= f.radio_button :is_deleted, 'false' %>
<%= f.label :is_deleted, '有効', value: false %>
<%= f.radio_button :is_deleted, 'true' %>
<%= f.label :is_deleted, '退会', value: true %>
</div>
</div>

<div class="form-froup row">
<div class="col-3 col-form-label"></div>
<div class="col-auto">
<%= f.submit '変更を保存',class:"btn btn-success" %>
</div>
<% end %>
</div>

</div>

app/views/admin/customers/index.html.erb
<div class="container">
<div class="col-2 mt-5 mb-5 secondary text-center">
<h2>会員一覧</h2>
</div>
</div>


   <div class="container">
        <table class="table col-10 mx-auto">
            <thead class="thead-light">
                <tr>
                 <th>会員ID</th>
                 <th>氏名</th>
                 <th>メールアドレス</th>
                 <th>ステータス</th>
                </tr>
            </thead>
        
            <tbody>
                <% @customers.each do |customer| %>
                <tr>
                  <td><%= customer.id %></td>
                  <td><u><%= link_to "#{customer.full_name}", admin_customer_path(customer.id), class: "text" %></u></td>
                  <td><%= customer.email %></td>
                  <% if customer.is_deleted %>
                　<td><span class="text-muted">退会</span></td>
                  <% else %>
                　<td><span class="text-success">有効</span></td>
                  <% end %>
                </tr>
                <% end %>
            </tbody>
        </table>
        
    </div>
    
    <div class="container text-align-center">
    <%= paginate @customers %>
    </div>
    

app/views/admin/customers/show.html.erb
<div class="container">
<div class="col-5 mt-5 mb-5 secondary text-center">
<h2><%= @customer.full_name %>さんの会員詳細</h2>
</div>
</div>

<div class="container">
<div class="col-md-7">
    
<div class="field row pb-3">
<label for ="customer_id" class="col-3">会員ID</label>
<div class="col-9">
<%= @customer.id %>
</div>
</div>

<div class="field row pb-3">
<label for ="customer_name" class="col-3">氏名</label>
<div class="col-9">
<%= @customer.last_name %> <%= @customer.first_name %>
</div>
</div>

<div class="field row pb-2">
<label for ="customer_name_kana" class="col-3">フリガナ</label>
<div class="col-9">
<%= @customer.last_name_kana %> <%= @customer.first_name_kana %>
</div>
</div>

<div class="field row pb-3">
<label for ="customer_postal_code" class="col-3">郵便番号</label>
<div class="col-9">
<%= @customer.postal_code %>
</div>
</div>

<div class="field row pb-3">
<label for ="customer_address" class="col-3">住所</label>
<div class="col-9">
<%= @customer.address %>
</div>
</div>

<div class="field row pb-3">
<label for ="customer_telephone_number" class="col-3">電話番号</label>
<div class="col-9">
<%= @customer.telephone_number %>
</div>
</div>

<div class="field row pb-3">
<label for ="customer_email" class="col-3">メールアドレス</label>
<div class="col-9">
<%= @customer.email %>
</div>
</div>

<div class="field row pb-3">
<label for ="customer_status" class="col-3">会員ステータス</label>
<div class="col-9">
<% if @customer.is_deleted %>
<p class="text-muted">退会</p>
<% else %>
<p class="text-success">有効</p>
<% end %>
</div>
</div>

<%= link_to "編集する", edit_admin_customer_path(@customer.id), class:"btn btn-success mr-3" %>
<%= link_to "注文履歴一覧を見る", admin_root_path, class:"btn btn-primary" %>

</div>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>