config/routes.rb
Rails.application.routes.draw do
    
  namespace :admin do
    resources :order_details, only: [:update]
  end
  
  namespace :admin do
    resources :orders, only: [:show, :update]
  end
  
  namespace :admin do
    resources :customers
  end
  
  namespace :admin do
    resources :genres
  end
  
  namespace :admin do
    resources :items
  end
  
  namespace :admin do
  root  "homes#top"
  end

  scope module: 'public' do
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  
  scope module: 'public' do
      post "orders/confirm", to: "orders#confirm"
      get "orders/complete", to: "orders#complete"
      resources :orders
  end
  
  scope module: 'public' do
    delete '/cart_items/destroy_all', to: "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  
  scope module: 'public' do
      get '/customers/mypage', to: "customers#show"
      get '/customers/information/edit', to: "customers#edit"
      patch '/customers/information', to: "customers#update"
      get '/customers/unsubscribe', to: "customers#unsubscribe"
      patch '/customers/withdraw', to: "customers#withdraw"
  end
  
  scope module: 'public' do
      resources :items, only: [:index, :show]
  end
  

  scope module: 'public' do
  root to: "homes#top"
  get '/about', to: "homes#about"
  end

  devise_for :customers, path: 'customers', controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  
  devise_for :admin, skip: [:registrations, :passwords], path: 'admin', controllers: {
  sessions: "admin/sessions"
 }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    
    def full_address
    self.postal_code + " " + self.address + " " + self.name
    end
    
    def address_display
       '〒' + postal_code + ' ' + address + ' ' + name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :customer
    
    def sum_of_price
        item.add_tax_price*amount  
    end  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items
  has_many :orders
  has_many :addresses
  
   def full_name
         self.last_name + " " + self.first_name
   end
   
   def full_name_kana
       self.last_name_kana + " " + self.first_name_kana
   end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    
    has_one_attached :image
    belongs_to :genre
    has_many :cart_items
    has_many :order_details
    

    def add_tax_price
        (self.price * 1.10).round
    end
    
end

app/models/order.rb
class Order < ApplicationRecord
 belongs_to :customer
 has_many :order_details
 
 enum payment_method:{ credit_card: 0, transfer: 1 }
 enum status: { waiting: 0, checking: 1, making: 2, preparing: 3, shipped: 4 }
 
 def full_name
         self.last_name + " " + self.first_name
 end
 

def sum_of_price
        item.add_tax_price*amount  
end  

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    
    enum making_status: { impossible: 0, waiting: 1, making: 2, finish: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def new
    @genre = Genre.new
  end
  
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    
    if  @genre.update(genre_params)
        redirect_to admin_genres_path
        flash[:notice] = "ジャンルが更新されました。"
    else
        render :edit
    end
    
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.all
    @customer = Customer.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
    @genres = Genre.all
  end
  
  def index
    @items = Item.page(params[:page]).per(10)
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @genres = Genre.all
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
     @item = Item.find(params[:id])
    
    if  @item.update!(item_params)
        redirect_to admin_item_path(@item.id)
        flash[:notice] = "商品が更新されました。"
    else
        render :edit
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details

    if @order.update(status: params[:order][:status])
      @order_details.update_all(making_status: 1)  if @order.status == "checking"
      redirect_to admin_order_path(@order.id)
    end
    
  end
  
  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :total_payment, 
         :payment_method, :status, :address_id, :full_address)
  end
  
  def order_detail_params
    params.require(:order_detail).permit(:item_id, :order_id, :amount, :price, :making_status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
  
protected

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    
    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, 
                                      :postal_code, :address, :telephone_number])
    end
    
    
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/create.html.erb
<h1>Admin::Genres#create</h1>
<p>Find me in app/views/admin/genres/create.html.erb</p>

app/views/admin/genres/edit.html.erb
<div class="container">
<div class="col-2 mt-5 secondary text-center">
<h2>ジャンル編集</h2>
</div>
</div>


<%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
<div class="container">
<div class="row mt-5">
<label for="genre" class="col col-lg-2">ジャンル名</label>
<div class="col-md-auto">
<%= f.text_field :name %>
</div>
<div class="col col-lg-2">
<%= f.submit '変更を保存', class: 'btn btn-success' %>
</div>
  
<% end %>

app/views/admin/genres/index.html.erb
<div class="container">
<div class="col-4 mt-5 mb-5 secondary text-center">
<h2>ジャンル一覧・追加</h2>
</div>
</div>


<%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
 <div class="container">
 <div class="row mt-5">
  <label for="genre" class="col col-lg-2">ジャンル名</label>
  <div class="col-md-auto">
  <%= f.text_field :name %>
  </div>
  <div class="col col-lg-2">
  <%= f.submit '新規登録', class: 'btn btn-success' %>
  </div>
  </div>
<% end %>


　　　　<div class="row col-md-3">
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th>ジャンル</th>
                    <th></th>
                </tr>
            </thead>
            <% @genres.each do |genre| %>
            <tbody>
                <tr>
                  <td><%= genre.name %></td>
                  <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class:"btn btn-success" %></td>
                </tr>
            </tbody>
            <% end %>
        </table>
        </div>




</div>
</div>

app/views/admin/genres/update.html.erb
<h1>Admin::Genres#update</h1>
<p>Find me in app/views/admin/genres/update.html.erb</p>

app/views/admin/items/create.html.erb
<h1>Admin::Items#create</h1>
<p>Find me in app/views/admin/items/create.html.erb</p>

app/views/admin/items/edit.html.erb
<div class="container">
<div class="col-2 mt-5 mb-5 secondary text-center">
<h2>商品編集</h2>
</div>
</div>

<div class="container">
<div class="col-7 mx-auto">
    
<%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>

<div class="form-group row">
<label for ="item_image" class="col-3 col-form-label">商品画像</label>
<div class="col-9">
<%= f.file_field :image, class:"form-control-file", accept: "image/*" %>
</div>
</div>

<div class="form-group row">
<label for ="item_name" class="col-3 col-form-label">商品名</label>
<div class="col-9">
<%= f.text_field :name, class:"form-control" %>
</div>
</div>

<div class="form-group row">
<label for ="item-introduction" class="col-3 col-form-label">商品説明</label>
<div class="col-9">
<%= f.text_area :introduction,class:"form-control" %>
</div>
</div>

<div class="form-group row">
<label for ="item-genre" class="col-3 col-form-label">ジャンル</label>
<div class="col-9">
<%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "-- 選択して下さい --" %>
</div>
</div>

<div class="form-group row">
<label for ="item_name" class="col-3 col-form-label">税抜価格<br>※(,)無し</label>
<div class="col-7">
<%= f.text_field :price, class: "form-control"%>
</div>
<div class="col-2 align-items-center">円</div>
</div>

<div class="form-group row">
<label for ="is_active" class="col-3 col-form-label">販売ステータス</label>
<div class="col-9">
<%= f.radio_button :is_active, '1' %>
<%= f.label :is_active, '販売中', value: 1%>
<%= f.radio_button :is_active, '0' %>
<%= f.label :is_active, '販売停止中', value: 0 %>
</div>
</div>

<div class="form-group postion-center">
<%= f.submit '変更を保存',class:"btn btn-success" %>
</div>


<% end %>

</div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
<div class="col-2 mt-5 secondary text-center">
<h2>商品一覧</h2>
</div>
</div>

<div class="col-10 text-right">
<%= link_to new_admin_item_path do %>
<h2><i class="fas fa-plus-circle" style="color: black;"></i></h2>
<% end %>
</div>
</div>
</div>

<div class="container">
<table class="table col-10 mx-auto table-borderless">
    <thead class="thead-light">
        <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
        </tr>
    </thead>
   
    <tbody>
        <% @items.each do |item| %>
        <tr>
            <td><%= item.id %></td>
            <td><u><%= link_to "#{item.name}", admin_item_path(item.id), class: "text" %></u></td>
            <td><%= item.price.to_s(:delimited) %></td>
            <td><%= item.genre.name %></td>
            <% if item.is_active %>
            <td><span class="text-success">販売中</span></td>
            <% else %>
            <td><span class="text-muted">販売停止中</span></td>
            <% end %>
        </tr>
        <% end %>
    </tbody>
    
</table>
</div>
</div>

<div class="container col-2 mt-5">
<div class="text-center">
<%= paginate @items %>
</div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
<div class="col-4 mt-5 mb-5 secondary text-center">
<h2>商品新規登録</h2>
</div>
</div>

<%= form_with model: @item, url: admin_items_path, method: :post do |f| %>

<div class="container">
<div class="col-7 mx-auto">
 
<div class="form-group row">
<label for ="item_image" class="col-3 col-form-label">商品画像</label>
<div class="col-9 pt-1">
<%= f.file_field :image, class:"form-control-file", accept: "image/*" %>
</div>
</div>

<div class="form-group row">
<div class="col-3 col-form-label"><%= f.label :name, "商品名" %></div>
<div class="col-9">
<%= f.text_field :name, class:"form-control" %>
</div>
</div>

<div class="form-group row">
<div class="col-3 col-form-label"><%= f.label :introduction, "商品説明" %></div>
<div class="col-9">
<%= f.text_area :introduction,class:"form-control" %>
</div>
</div>

<div class="form-group row">
<div class="col-3 col-form-label"><%= f.label :genre_id, "ジャンル" %></div>
<div class="col-9 pt-1">
<%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "-- 選択して下さい --" %>
</div>
</div>

<div class="form-group row">
<div class="col-3 col-form-label"><%= f.label :price, "税抜価格" %></div>
<div class="col-7">
<%= f.text_field :price, class:"form-control"%>
</div>
<div class="col-2 align-items-center">円</div>
</div>

<div class="form-group row">
<div class="col-md-3 col-form-label"><%= f.label :is_active, "販売ステータス" %></div>
<div class="col-md-9 pt-1">
<%= f.radio_button :is_active, 'true' %>
<%= f.label :is_active, '販売中', value: true %>
<%= f.radio_button :is_active, 'false' %>
<%= f.label :is_active, '販売停止中', value: false %>
</div>
</div>

<div class="form-group">
<%= f.submit '新規登録',class:"btn btn-success" %>
</div>


<% end %>

 </div>
 </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
<div class="col-2 mt-5 mb-5 secondary text-center">
<h2>商品詳細</h2>
</div>
</div>

<div class="container">
<div class="row mx-auto">
    
<div class="col-4 text-right">
<%= image_tag @item.image, size: "200x200" %>
</div>

<div class="col-8">
<div class="filed row mb-2">
<label for ="item_name" class="col-3">商品名</label>
<div class="col-9">
<%= @item.name %>
</div>
</div>

<div class="field row mb-2">
<label for ="item_introduction" class="col-3">商品説明</label>
<div class="col-9">
<%= @item.introduction %>
</div>
</div>

<div class="field row mb-2">
<label for ="item_genre" class="col-3">ジャンル</label>
<div class="col-9">
<%= @item.genre.name %>
</div>
</div>

<div class="field row mb-2">
<label for ="item_price" class="col-3">税込価格<br>(税抜価格)</label>
<div class="col-9 pt-2">
<%= @item.add_tax_price.to_s(:delimited) %>
(<%= @item.price.to_s(:delimited) %>) 円
</div>
</div>

<div class="field row mb-2">
<label for ="item_status" class="col-3">販売ステータス</label>
<div class="col-9">
<% if @item.is_active %>
<p class="text-success">販売中</p>
<% else %>
<p class="text-muted">販売停止中</p>
<% end %>
</div>
</div>

<%= link_to "編集する", edit_admin_item_path(@item.id), class:"btn btn-success" %>

</div>
</div>
</div>

app/views/admin/items/update.html.erb
<h1>Admin::Items#update</h1>
<p>Find me in app/views/admin/items/update.html.erb</p>

app/views/admin/orders/show.html.erb
<div class="container">
<div class="col-3 mt-5 mb-5 secondary text-center">
<h2>注文履歴詳細</h2>
</div>
</div>

<div class="container">

<div class="filed row mb-1">
<label for ="customer_name" class="col-2"><h5><strong>購入者</strong></h5></label>
<div class="col-10">
<h5><%= @order.customer.full_name %></h5>
</div>
</div>

<div class="filed row mb-1">
<label for ="customer_name" class="col-2"><h5><strong>注文日</strong></h5></label>
<div class="col-10">
<h5><%= @order.created_at.strftime('%Y/%m/%d') %></h5>
</div>
</div>

<div class="filed row mb-1">
<label for ="customer_name" class="col-2"><h5><strong>配送先</strong></h5></label>
<div class="col-10">
<h5>〒<%= @order.postal_code %><%= @order.address %><br><%= @order.name%></h5>
</div>
</div>

<div class="filed row mb-1">
<label for ="customer_name" class="col-2"><h5><strong>支払方法</strong></h5></label>
<div class="col-10">
<h5><%= @order.payment_method_i18n %></h5>
</div>
</div>

<%= form_with model: @order, url: admin_order_path(@order.id), method: :patch do |f| %>
<div class="form-group row">
<label for ="status" class="col-2"><h5><strong>注文ステータス</strong></h5></label>
<div class="ml-2 pl-2">
<%= f.select :status, Order.statuses_i18n.keys.map{|k| [I18n.t("enums.order.status.#{k}"), k]} %>
</div>
<div class="col-2">
<%= f.submit '更新',class:"btn btn-success btn-sm" %>
</div>
<% end %>
</div>

<div class="row">
<div class="col-8">
<table class="table">
    <thead class="thead-secondary">
        <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
        </tr>
    </thead>
    <tbody>
        <% @order.order_details.each do |order_detail| %>
        <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.price.to_s(:delimited) %></td>
            <td><%= order_detail.amount %></td>
            <td><%= order_detail.price.to_s(:delimited) %></td>
            <td><%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch do |f| %>
                <%= f.select :making_status, OrderDetail.making_statuses_i18n.keys.map{|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
                <%= f.submit '更新',class:"btn btn-success btn-sm ml-2" %>
                <% end %></td>
        </tr>
        <% end %>
    </tbody>
</table>
</div>

<div class="col-3 d-flex align-items-end">
<table class="table table-borderless">
    <tr>
        <td><strong>商品合計</strong></td>
        <td><%= @order.total_payment.to_s(:delimited) %>円</td>
    </tr>
    <tr>
        <td><strong>送料</strong></td>
        <td><%= @order.shipping_cost %>円</td>
    </tr>
    <tr>
        <td><strong>請求金額合計</strong></td>
        <td><strong><%= (@order.shipping_cost + @order.total_payment ).to_s(:delimited) %>円</strong></td>
    </tr>
</table>
</div>
</div>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>