config/routes.rb
Rails.application.routes.draw do
    
  namespace :admin do
    resources :order_details, only: [:update]
  end
  
  namespace :admin do
    resources :orders, only: [:show, :update]
  end
  
  namespace :admin do
    resources :customers
  end
  
  namespace :admin do
    resources :genres
  end
  
  namespace :admin do
    resources :items
  end
  
  namespace :admin do
  root  "homes#top"
  end

  scope module: 'public' do
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  
  scope module: 'public' do
      post "orders/confirm", to: "orders#confirm"
      get "orders/complete", to: "orders#complete"
      resources :orders
  end
  
  scope module: 'public' do
    delete '/cart_items/destroy_all', to: "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  
  scope module: 'public' do
      get '/customers/mypage', to: "customers#show"
      get '/customers/information/edit', to: "customers#edit"
      patch '/customers/information', to: "customers#update"
      get '/customers/unsubscribe', to: "customers#unsubscribe"
      patch '/customers/withdraw', to: "customers#withdraw"
  end
  
  scope module: 'public' do
      resources :items, only: [:index, :show]
  end
  

  scope module: 'public' do
  root to: "homes#top"
  get '/about', to: "homes#about"
  end

  devise_for :customers, path: 'customers', controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  
  devise_for :admin, skip: [:registrations, :passwords], path: 'admin', controllers: {
  sessions: "admin/sessions"
 }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    
    def full_address
    self.postal_code + " " + self.address + " " + self.name
    end
    
    def address_display
       '〒' + postal_code + ' ' + address + ' ' + name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :customer
    
    def sum_of_price
        item.add_tax_price*amount  
    end  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items
  has_many :orders
  has_many :addresses
  
   def full_name
         self.last_name + " " + self.first_name
   end
   
   def full_name_kana
       self.last_name_kana + " " + self.first_name_kana
   end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    
    has_one_attached :image
    belongs_to :genre
    has_many :cart_items
    has_many :order_details
    

    def add_tax_price
        (self.price * 1.10).round
    end
    
end

app/models/order.rb
class Order < ApplicationRecord
 belongs_to :customer
 has_many :order_details
 
 enum payment_method:{ credit_card: 0, transfer: 1 }
 enum status: { waiting: 0, checking: 1, making: 2, preparing: 3, shipped: 4 }
 
 def full_name
         self.last_name + " " + self.first_name
 end
 

def sum_of_price
        item.add_tax_price*amount  
end  

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    
    enum making_status: { impossible: 0, waiting: 1, making: 2, finish: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def new
    @genre = Genre.new
  end
  
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    
    if  @genre.update(genre_params)
        redirect_to admin_genres_path
        flash[:notice] = "ジャンルが更新されました。"
    else
        render :edit
    end
    
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.all
    @customer = Customer.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
    @genres = Genre.all
  end
  
  def index
    @items = Item.page(params[:page]).per(10)
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @genres = Genre.all
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
     @item = Item.find(params[:id])
    
    if  @item.update!(item_params)
        redirect_to admin_item_path(@item.id)
        flash[:notice] = "商品が更新されました。"
    else
        render :edit
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    
    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, 
                                      :postal_code, :address, :telephone_number])
    end
    
    
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
  <script src="https://kit.fontawesome.com/1871c9c7c6.js" crossorigin="anonymous"></script>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/">LOGO</a>
          <% if customer_signed_in? %>
          <div class="col-7 text-center ml-5">ようこそ、<%= current_customer.last_name %>さん　!</div>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              
            <% if customer_signed_in? %>
            <li class="nav-item">
              <%= link_to "マイページ", customers_mypage_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '商品一覧', items_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'カート', cart_items_path, class: 'nav-link text-dark' %>
            </li>
             <li class="nav-item">
              <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            
            <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "注文履歴一覧", admin_root_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            
            <% else %>
            <li class="nav-item">
              <%= link_to "About", about_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <main>
    <div class="text-dark"><%= flash[:notice] %></div>
    <%= yield %>
    </main>
  
  </body>
  
</html>